
#ifdef check
   #undef check
#endif

#include "msrp/MessageSessionBase.hxx"

using namespace msrp;
using namespace std;
using namespace boost;

MessageSessionBase::MessageSessionBase(const Message& m) :
   mMessage(m), mSize(0), mTransferred(0), mComplete(false), mInterrupted(false)
{
   try
   {
      if (mMessage.exists<ByteRange>())
      {
         const ByteRangeTuple& br = mMessage.header<ByteRange>();

         if (br.total != ByteRange::Unknown)
         {
            mSize = br.total;
         }
      }
   }
   catch (const ParseException&)
   {}
}

MessageSessionBase::~MessageSessionBase()
{}

size_t
MessageSessionBase::size() const
{
   return mSize;
}

size_t
MessageSessionBase::transferred() const
{
   return mTransferred;
}

bool
MessageSessionBase::complete() const
{
   return mComplete;
}

bool
MessageSessionBase::interrupted() const
{
   return mInterrupted;
}

Message&
MessageSessionBase::message()
{
   return mMessage;
}

const Message&
MessageSessionBase::message() const
{
   return mMessage;
}

const string
MessageSessionBase::messageId() const
{
   try
   {
      return message().header<MessageId>();
   }
   catch (const ParseException&)
   {}

   return std::string();
}

signal0<void>&
MessageSessionBase::onComplete()
{
   return mCompleteEvent;
}

const posix_time::ptime&
MessageSessionBase::lastTransfer() const
{
   return mLastTransfer;
}

// Copyright (c) 2006, 2007 Chris L. Bond.
// 
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
// 
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.
