#ifndef MSRP_MIME_HXX
#define MSRP_MIME_HXX

#include <ostream>
#include <map>
#include <string>

namespace msrp
{

class Mime
{
   public:
      Mime()
      {}

      // Parse a full mime type
      Mime(const std::string& mime);

      Mime(const std::string& type, const std::string& subtype) :
         mType(type), mSubtype(subtype)
      {}

      Mime(const std::pair<std::string, std::string>& pair) :
         mType(pair.first), mSubtype(pair.second)
      {}

      const std::string& type() const { return mType; }
      std::string& type() { return mType; }

      const std::string& subtype() const { return mSubtype; }
      std::string& subtype() { return mSubtype; }

      const std::map<std::string, std::string>& params() const { return mParams; }
      std::map<std::string, std::string>& params() { return mParams; }

      bool operator<(const Mime&) const;

      bool operator==(const Mime&) const;

   private:
      std::string mType;
      std::string mSubtype;

      std::map<std::string, std::string> mParams;
};

std::ostream&
operator<<(std::ostream&, const Mime&);

}

#endif

// Copyright (c) 2006, 2007 Chris L. Bond.
// 
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
// 
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.
